[package]
name = "crawl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

reqwest = "0.12.2"
select = "0.6.0"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
